### ISSUE TITLE
node_curve.cc(20): error C2065: 'Handle': undeclared identifier

### ISSUE THREAD

**Issue by thedave42** [MystK/node-curve25519#1]
Getting this error when I try to build either on Windows 10 or MacOS 14.5.  Please see attached npm logs.
[2019-06-25T01_53_39_250Z-debug.log](https://github.com/MystK/node-curve25519/files/3323239/2019-06-25T01_53_39_250Z-debug.log)
[2019-06-25T01_50_17_354Z-debug.log](https://github.com/MystK/node-curve25519/files/3323240/2019-06-25T01_50_17_354Z-debug.log)

**Comment by MystK** [comment]
Do you have the windows build tools installed?

**Comment by thedave42** [comment]
Yes. I did try uninstalling and reinstalling the windows build tools and still get the same error.

**Comment by MystK** [comment]
It works fine for me on both Windows 10 and MacOS, so it's your environment.

Your debug logs tell me you didn't install windows-build-tools properly.

Can you try `npm i bson` ?

**Comment by thedave42** [comment]
That did succeed.

```
C:\tools\git-repos>npm i bson
npm WARN saveError ENOENT: no such file or directory, open 'C:\tools\git-repos\package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open 'C:\tools\git-repos\package.json'
npm WARN git-repos No description
npm WARN git-repos No repository field.
npm WARN git-repos No README data
npm WARN git-repos No license field.

+ bson@4.0.2
added 5 packages from 6 contributors and audited 5 packages in 0.849s
found 0 vulnerabilities

```
I use nvm so I also tried with a new node environment and installed windows-build-tools from scratch.  I'm still getting an error with the build.  

******Nevermind**.  This is a different error than I was getting before and I know how to fix it.  The issue I was trying to solve was an compilation error.  I will create a clean environment with the correct windows build tools and SDK and verify I am still  having the compile issue*******


_I've pasted the screen output the point I start with a clean node environment until the error, and I've attached the log here.  Unfortunately I'm not a c++ dev so I'm having some issues with troubleshooting these error messages.  If you can see something wrong with my environment please let me know.  Thank you for the help!_

```
C:\tools\git-repos>nvm install 12.4.0
Downloading node.js version 12.4.0 (64-bit)...
Complete
Creating C:\Users\dave\AppData\Roaming\nvm\temp

Downloading npm version 6.9.0... Complete
Installing npm v6.9.0...

Installation complete. If you want to use this version, type

nvm use 12.4.0

C:\tools\git-repos>nvm use 12.4.0
Now using node v12.4.0 (64-bit)

C:\tools\git-repos>npm i -g windows-build-tools

> windows-build-tools@5.1.0 postinstall C:\Program Files\nodejs\node_modules\windows-build-tools
> node ./dist/index.js



Downloading python-2.7.15.amd64.msi
[>                                            ] 0.0% (0 B/s)
Downloaded python-2.7.15.amd64.msi. Saved to C:\Users\dave\.windows-build-tools\python-2.7.15.amd64.msi.
Downloading vs_BuildTools.exe
[>                                            ] 0.0% (0 B/s)
Downloaded vs_BuildTools.exe. Saved to C:\Users\dave\.windows-build-tools\vs_BuildTools.exe.

Starting installation...
Launched installers, now waiting for them to finish.
This will likely take some time - please be patient!

Status from the installers:
---------- Visual Studio Build Tools ----------
Successfully installed Visual Studio Build Tools.
------------------- Python --------------------
Action ended 8:15:59: SetDLLDirToSystem32. Return value 1.
Action start 8:15:59: WindowsFolder.30729.01.Microsoft_VC90_CRT_x64.SP.25A3A9CB_4A28_34E8_87BE_4A9057266812.
Action ended 8:15:59: WindowsFolder.30729.01.Microsoft_VC90_CRT_x64.SP.25A3A9CB_4A28_34E8_87BE_4A9057266812. Return value 1.
Action start 8:15:59: WindowsFolder.30729.01.policy_9_0_Microsoft_VC90_CRT_x64.SP.E83531BF_FAC2_33DD_8232_0506BF31308B.
Action ended 8:15:59: WindowsFolder.30729.01.policy_9_0_Microsoft_VC90_CRT_x64.SP.E83531BF_FAC2_33DD_8232_0506BF31308B. Return value 1.

Now configuring the Visual Studio Build Tools and Python...

All done!

+ windows-build-tools@5.1.0
added 145 packages from 99 contributors in 15.229s

C:\tools\git-repos>git clone https://github.com/MystK/node-curve25519.git
Cloning into 'node-curve25519'...
remote: Enumerating objects: 80, done.
remote: Total 80 (delta 0), reused 0 (delta 0), pack-reused 80
Unpacking objects: 100% (80/80), done.

C:\tools\git-repos>cd node-curve25519

C:\tools\git-repos\node-curve25519>npm i

> curve25519-n2@1.1.3 install C:\tools\git-repos\node-curve25519
> node-gyp rebuild


C:\tools\git-repos\node-curve25519>if not defined npm_config_node_gyp (node "C:\Users\dave\AppData\Roaming\nvm\v12.4.0\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\dave\AppData\Roaming\nvm\v12.4.0\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\15.0\Bin\MSBuild.exe ENOENT
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
gyp ERR! stack     at onErrorNT (internal/child_process.js:456:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:84:9)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\dave\\AppData\\Roaming\\nvm\\v12.4.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\tools\git-repos\node-curve25519
gyp ERR! node -v v12.4.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! curve25519-n2@1.1.3 install: `node-gyp rebuild`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the curve25519-n2@1.1.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dave\AppData\Roaming\npm-cache\_logs\2019-06-25T15_17_08_408Z-debug.log

C:\tools\git-repos\node-curve25519>
```

[2019-06-25T15_17_08_408Z-debug.log](https://github.com/MystK/node-curve25519/files/3326013/2019-06-25T15_17_08_408Z-debug.log)

**Comment by thedave42** [comment]
Ok, here's the error I originally reported.  I can repeat it consistently now.  If there's something about my environment that's wrong, I can't understand what from these error messages.  This is the screen message from when I clone the repo to when I build with npm.  I've also attached the error log. 

```
C:\tools\git-repos>git clone https://github.com/MystK/node-curve25519.git
Cloning into 'node-curve25519'...
remote: Enumerating objects: 80, done.
remote: Total 80 (delta 0), reused 0 (delta 0), pack-reused 80
Unpacking objects: 100% (80/80), done.

C:\tools\git-repos>cd node-curve25519

C:\tools\git-repos\node-curve25519>npm i

> curve25519-n2@1.1.3 install C:\tools\git-repos\node-curve25519
> node-gyp rebuild


C:\tools\git-repos\node-curve25519>if not defined npm_config_node_gyp (node "C:\Users\dave\AppData\Roaming\nvm\v12.4.0\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\dave\AppData\Roaming\nvm\v12.4.0\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  node_curve.cc
  win_delay_load_hook.cc
c:\tools\git-repos\node-curve25519\node_curve.cc(20): error C2065: 'Handle': undeclared identifier [C:\tools\git-repos\
node-curve25519\build\curve.vcxproj]
c:\tools\git-repos\node-curve25519\node_curve.cc(20): error C2275: 'v8::Object': illegal use of this type as an express
ion [C:\tools\git-repos\node-curve25519\build\curve.vcxproj]
  c:\users\dave\.node-gyp\12.4.0\include\node\v8.h(3356): note: see declaration of 'v8::Object'
c:\tools\git-repos\node-curve25519\node_curve.cc(20): error C2059: syntax error: ')' [C:\tools\git-repos\node-curve2551
9\build\curve.vcxproj]
c:\tools\git-repos\node-curve25519\node_curve.cc(28): error C2661: 'v8::Value::ToObject': no overloaded function takes
0 arguments [C:\tools\git-repos\node-curve25519\build\curve.vcxproj]
c:\tools\git-repos\node-curve25519\node_curve.cc(29): error C2661: 'v8::Value::ToObject': no overloaded function takes
0 arguments [C:\tools\git-repos\node-curve25519\build\curve.vcxproj]
c:\tools\git-repos\node-curve25519\node_curve.cc(30): error C2661: 'v8::Value::ToObject': no overloaded function takes
0 arguments [C:\tools\git-repos\node-curve25519\build\curve.vcxproj]
c:\tools\git-repos\node-curve25519\node_curve.cc(34): error C2065: 'Handle': undeclared identifier [C:\tools\git-repos\
node-curve25519\build\curve.vcxproj]
c:\tools\git-repos\node-curve25519\node_curve.cc(34): error C2275: 'v8::Object': illegal use of this type as an express
ion [C:\tools\git-repos\node-curve25519\build\curve.vcxproj]
  c:\users\dave\.node-gyp\12.4.0\include\node\v8.h(3356): note: see declaration of 'v8::Object'
c:\tools\git-repos\node-curve25519\node_curve.cc(34): error C2065: 'target': undeclared identifier [C:\tools\git-repos\
node-curve25519\build\curve.vcxproj]
c:\tools\git-repos\node-curve25519\node_curve.cc(34): error C2182: 'init': illegal use of type 'void' [C:\tools\git-rep
os\node-curve25519\build\curve.vcxproj]
c:\tools\git-repos\node-curve25519\node_curve.cc(34): error C2448: 'init': function-style initializer appears to be a f
unction definition [C:\tools\git-repos\node-curve25519\build\curve.vcxproj]
c:\tools\git-repos\node-curve25519\node_curve.cc(40): warning C4312: 'type cast': conversion from 'int' to 'node::addon
_register_func' of greater size [C:\tools\git-repos\node-curve25519\build\curve.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\dave\AppData\Roaming\nvm\v12.4.0\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\dave\\AppData\\Roaming\\nvm\\v12.4.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\tools\git-repos\node-curve25519
gyp ERR! node -v v12.4.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! curve25519-n2@1.1.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the curve25519-n2@1.1.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dave\AppData\Roaming\npm-cache\_logs\2019-06-25T23_29_49_243Z-debug.log

C:\tools\git-repos\node-curve25519>

```
[2019-06-25T23_29_49_243Z-debug.log](https://github.com/MystK/node-curve25519/files/3327579/2019-06-25T23_29_49_243Z-debug.log)

**Comment by MystK** [comment]
What is your goal? to install node-curve25519 as a dependency or to build node-curve25519 and work on it?

**Comment by thedave42** [comment]
To install it as a dependency.  The package node-appletv depends on it.  I get the same error message when I try to install node-appletv and it reaches node-curve25519.

Here's is the trace when I try to install node-appletv and it reaches curve25519, just after compiling libsodium:

```
Prebuild steps completed. Binary libsodium distribution installed in ./deps/build
C:\Program Files\nodejs\appletv -> C:\Program Files\nodejs\node_modules\node-appletv\bin\appletv

> curve25519-n2@1.1.3 install C:\Program Files\nodejs\node_modules\node-appletv\node_modules\curve25519-n2
> node-gyp rebuild


C:\Program Files\nodejs\node_modules\node-appletv\node_modules\curve25519-n2>if not defined npm_config_node_gyp (node "C:\Users\dave\AppData\Roaming\nvm\v12.4.0\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\dave\AppData\Roaming\nvm\v12.4.0\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  node_curve.cc
  win_delay_load_hook.cc
..\node_curve.cc(20): error C2065: 'Handle': undeclared identifier [C:\Program Files\nodejs\node_modules\node-appletv\n
ode_modules\curve25519-n2\build\curve.vcxproj]
..\node_curve.cc(20): error C2275: 'v8::Object': illegal use of this type as an expression [C:\Program Files\nodejs\nod
e_modules\node-appletv\node_modules\curve25519-n2\build\curve.vcxproj]
  C:\Users\dave\.node-gyp\12.4.0\include\node\v8.h(3356): note: see declaration of 'v8::Object'
..\node_curve.cc(20): error C2059: syntax error: ')' [C:\Program Files\nodejs\node_modules\node-appletv\node_modules\cu
rve25519-n2\build\curve.vcxproj]
..\node_curve.cc(28): error C2661: 'v8::Value::ToObject': no overloaded function takes 0 arguments [C:\Program Files\no
dejs\node_modules\node-appletv\node_modules\curve25519-n2\build\curve.vcxproj]
..\node_curve.cc(29): error C2661: 'v8::Value::ToObject': no overloaded function takes 0 arguments [C:\Program Files\no
dejs\node_modules\node-appletv\node_modules\curve25519-n2\build\curve.vcxproj]
..\node_curve.cc(30): error C2661: 'v8::Value::ToObject': no overloaded function takes 0 arguments [C:\Program Files\no
dejs\node_modules\node-appletv\node_modules\curve25519-n2\build\curve.vcxproj]
..\node_curve.cc(34): error C2065: 'Handle': undeclared identifier [C:\Program Files\nodejs\node_modules\node-appletv\n
ode_modules\curve25519-n2\build\curve.vcxproj]
..\node_curve.cc(34): error C2275: 'v8::Object': illegal use of this type as an expression [C:\Program Files\nodejs\nod
e_modules\node-appletv\node_modules\curve25519-n2\build\curve.vcxproj]
  C:\Users\dave\.node-gyp\12.4.0\include\node\v8.h(3356): note: see declaration of 'v8::Object'
..\node_curve.cc(34): error C2065: 'target': undeclared identifier [C:\Program Files\nodejs\node_modules\node-appletv\n
ode_modules\curve25519-n2\build\curve.vcxproj]
..\node_curve.cc(34): error C2182: 'init': illegal use of type 'void' [C:\Program Files\nodejs\node_modules\node-applet
v\node_modules\curve25519-n2\build\curve.vcxproj]
..\node_curve.cc(34): error C2448: 'init': function-style initializer appears to be a function definition [C:\Program F
iles\nodejs\node_modules\node-appletv\node_modules\curve25519-n2\build\curve.vcxproj]
..\node_curve.cc(40): warning C4312: 'type cast': conversion from 'int' to 'node::addon_register_func' of greater size
[C:\Program Files\nodejs\node_modules\node-appletv\node_modules\curve25519-n2\build\curve.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\dave\AppData\Roaming\nvm\v12.4.0\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\dave\\AppData\\Roaming\\nvm\\v12.4.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Program Files\nodejs\node_modules\node-appletv\node_modules\curve25519-n2
gyp ERR! node -v v12.4.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! curve25519-n2@1.1.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the curve25519-n2@1.1.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dave\AppData\Roaming\npm-cache\_logs\2019-06-26T00_01_53_717Z-debug.log

C:\tools\git-repos>
```



[2019-06-26T00_01_53_717Z-debug.log](https://github.com/MystK/node-curve25519/files/3327645/2019-06-26T00_01_53_717Z-debug.log)

**Comment by MystK** [comment]
Not sure why it's not working for you. I testing both on appletv and just installing curve25519 and it works fine for me.

```
Prebuild steps completed. Binary libsodium distribution installed in ./deps/build
C:\Program Files\nodejs\appletv -> C:\Program Files\nodejs\node_modules\node-appletv\bin\appletv

> curve25519-n2@1.1.3 install C:\Program Files\nodejs\node_modules\node-appletv\node_modules\curve25519-n2
> node-gyp rebuild


C:\Program Files\nodejs\node_modules\node-appletv\node_modules\curve25519-n2>if not defined npm_config_node_gyp (node "C:\Users\its\AppData\Roaming\nvm\v10.15.3\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\its\AppData\Roaming\nvm\v10.15.3\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  node_curve.cc
  win_delay_load_hook.cc
..\node_curve.cc(28): warning C4996: 'v8::Value::ToObject': was declared deprecated [C:\Program Files\nodejs\node_modules\node-appletv\node_modules\curve25519-n2\build\curve.vcxp
roj]
  C:\Users\its\.node-gyp\10.15.3\include\node\v8.h(10046): note: see declaration of 'v8::Value::ToObject'
..\node_curve.cc(29): warning C4996: 'v8::Value::ToObject': was declared deprecated [C:\Program Files\nodejs\node_modules\node-appletv\node_modules\curve25519-n2\build\curve.vcxp
roj]
  C:\Users\its\.node-gyp\10.15.3\include\node\v8.h(10046): note: see declaration of 'v8::Value::ToObject'
..\node_curve.cc(30): warning C4996: 'v8::Value::ToObject': was declared deprecated [C:\Program Files\nodejs\node_modules\node-appletv\node_modules\curve25519-n2\build\curve.vcxp
roj]
  C:\Users\its\.node-gyp\10.15.3\include\node\v8.h(10046): note: see declaration of 'v8::Value::ToObject'
     Creating library C:\Program Files\nodejs\node_modules\node-appletv\node_modules\curve25519-n2\build\Release\curve.lib and object C:\Program Files\nodejs\node_modules\node-ap
  pletv\node_modules\curve25519-n2\build\Release\curve.exp
  Generating code
  All 96 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  Finished generating code
  curve.vcxproj -> C:\Program Files\nodejs\node_modules\node-appletv\node_modules\curve25519-n2\build\Release\\curve.node
  curve.vcxproj -> C:\Program Files\nodejs\node_modules\node-appletv\node_modules\curve25519-n2\build\Release\curve.pdb (Full PDB)

> ed25519@0.0.4 install C:\Program Files\nodejs\node_modules\node-appletv\node_modules\ed25519
> node-gyp rebuild
```
```
npm i -g curve25519-n2

> curve25519-n2@1.1.3 install C:\Program Files\nodejs\node_modules\curve25519-n2
> node-gyp rebuild


C:\Program Files\nodejs\node_modules\curve25519-n2>if not defined npm_config_node_gyp (node "C:\Users\its\AppData\Roaming\nvm\v10.15.3\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\its\AppData\Roaming\nvm\v10.15.3\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  node_curve.cc
  win_delay_load_hook.cc
c:\program files\nodejs\node_modules\curve25519-n2\node_curve.cc(28): warning C4996: 'v8::Value::ToObject': was declared deprecated [C:\Program Files\nodejs\node_modules\curve255
19-n2\build\curve.vcxproj]
  c:\users\its\.node-gyp\10.15.3\include\node\v8.h(10046): note: see declaration of 'v8::Value::ToObject'
c:\program files\nodejs\node_modules\curve25519-n2\node_curve.cc(29): warning C4996: 'v8::Value::ToObject': was declared deprecated [C:\Program Files\nodejs\node_modules\curve255
19-n2\build\curve.vcxproj]
  c:\users\its\.node-gyp\10.15.3\include\node\v8.h(10046): note: see declaration of 'v8::Value::ToObject'
c:\program files\nodejs\node_modules\curve25519-n2\node_curve.cc(30): warning C4996: 'v8::Value::ToObject': was declared deprecated [C:\Program Files\nodejs\node_modules\curve255
19-n2\build\curve.vcxproj]
  c:\users\its\.node-gyp\10.15.3\include\node\v8.h(10046): note: see declaration of 'v8::Value::ToObject'
     Creating library C:\Program Files\nodejs\node_modules\curve25519-n2\build\Release\curve.lib and object C:\Program Files\nodejs\node_modules\curve25519-n2\build\Release\curve
  .exp
  Generating code
  All 96 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  Finished generating code
  curve.vcxproj -> C:\Program Files\nodejs\node_modules\curve25519-n2\build\Release\\curve.node
+ curve25519-n2@1.1.3
added 2 packages from 8 contributors and updated 1 package in 4.201s
```

**Comment by MystK** [comment]
Here is me running npm i in the repo and it also works
```
PS C:\dev\node-curve25519> npm i

> curve25519-n2@1.1.3 install C:\dev\node-curve25519
> node-gyp rebuild


C:\dev\node-curve25519>if not defined npm_config_node_gyp (node "C:\Users\its\AppData\Roaming\nvm\v10.15.3\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\its\AppData\Roaming\nvm\v10.15.3\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  node_curve.cc
  win_delay_load_hook.cc
c:\dev\node-curve25519\node_curve.cc(28): warning C4996: 'v8::Value::ToObject': was declared deprecated [C:\dev\node-curve25519\build\curve.vcxproj]
  c:\users\its\.node-gyp\10.15.3\include\node\v8.h(10046): note: see declaration of 'v8::Value::ToObject'
c:\dev\node-curve25519\node_curve.cc(29): warning C4996: 'v8::Value::ToObject': was declared deprecated [C:\dev\node-curve25519\build\curve.vcxproj]
  c:\users\its\.node-gyp\10.15.3\include\node\v8.h(10046): note: see declaration of 'v8::Value::ToObject'
c:\dev\node-curve25519\node_curve.cc(30): warning C4996: 'v8::Value::ToObject': was declared deprecated [C:\dev\node-curve25519\build\curve.vcxproj]
  c:\users\its\.node-gyp\10.15.3\include\node\v8.h(10046): note: see declaration of 'v8::Value::ToObject'
     Creating library C:\dev\node-curve25519\build\Release\curve.lib and object C:\dev\node-curve25519\build\Release\curve.exp
  Generating code
  All 96 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  Finished generating code
  curve.vcxproj -> C:\dev\node-curve25519\build\Release\\curve.node
npm notice created a lockfile as package-lock.json. You should commit this file.
added 2 packages from 8 contributors and audited 2 packages in 3.833s
found 0 vulnerabilities
```

**Comment by MystK** [comment]
I am pretty confident it's your environment. Unfortunately I don't know exactly why your environment is set up incorrectly.

**Comment by thedave42** [comment]
Yep, it probably is something about my environment.  I'll keep checking things.  What version of the MS Build Tools you're using to build?

```
VisualStudioVersion=14.0
INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE;C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared;C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt;
LIB=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB;C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\ucrt\x86;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x86;C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\um\x86;
LIBPATH=C:\Windows\Microsoft.NET\Framework\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB;C:\Program Files (x86)\Windows Kits\10\UnionMetadata;C:\Program Files (x86)\Windows Kits\10\References;C:\Program Files (x86)\Microsoft SDKs\Windows Kits\10\ExtensionSDKs\Microsoft.VCLibs\14.0\References\CommonConfiguration\neutral;

```

**Comment by thedave42** [comment]
I was able to successfully build when I switched my node environment to the same version I saw in your logs - 10.15.3.  I still get that error if I try and build in the latest node environment - 12.4.0.

**Comment by palasinio** [comment]
Hi, I have similar errors.
It is building with node 10 but not with node 12:
```
node_modules\curve25519-n2\node_curve.cc(20): error C2065: "Handle": nichtdeklarierter Bezeichner [C:\Users\chris\AppData\Roaming\npm\node_modules\homebridge-ranger\node_modules\curve25519-n2\build\curve.vcxproj]
node_modules\curve25519-n2\node_curve.cc(20): error C2275: "v8::Object": Ungültige Verwendung dieses Typs als Ausdruck [C:\Users\chris\AppData\Roaming\npm\node_modules\homebridge-ranger\node_modules\curve25519-n2\build\curve.vcxproj]
  node-gyp\cache\12.14.1\include\node\v8.h(3400): note: Siehe Deklaration von "v8::Object"
node_modules\curve25519-n2\node_curve.cc(20): error C2059: Syntaxfehler: ")" [C:\Users\chris\AppData\Roaming\npm\node_modules\homebridge-ranger\node_modules\curve25519-n2\build\curve.vcxproj]
node_modules\curve25519-n2\node_curve.cc(28): error C2661: "v8::Value::ToObject": Keine überladene Funktion akzeptiert 0 Argumente [C:\Users\chris\AppData\Roaming\npm\node_modules\homebridge-ranger\node_modules\curve25519-n2\build\curve.vcxproj]
node_modules\curve25519-n2\node_curve.cc(29): error C2661: "v8::Value::ToObject": Keine überladene Funktion akzeptiert 0 Argumente [C:\Users\chris\AppData\Roaming\npm\node_modules\homebridge-ranger\node_modules\curve25519-n2\build\curve.vcxproj]
node_modules\curve25519-n2\node_curve.cc(30): error C2661: "v8::Value::ToObject": Keine überladene Funktion akzeptiert 0 Argumente [C:\Users\chris\AppData\Roaming\npm\node_modules\homebridge-ranger\node_modules\curve25519-n2\build\curve.vcxproj]
node_modules\curve25519-n2\node_curve.cc(34): error C2065: "Handle": nichtdeklarierter Bezeichner [C:\Users\chris\AppData\Roaming\npm\node_modules\homebridge-ranger\node_modules\curve25519-n2\build\curve.vcxproj]
node_modules\curve25519-n2\node_curve.cc(34): error C2275: "v8::Object": Ungültige Verwendung dieses Typs als Ausdruck [C:\Users\chris\AppData\Roaming\npm\node_modules\homebridge-ranger\node_modules\curve25519-n2\build\curve.vcxproj]
  node-gyp\cache\12.14.1\include\node\v8.h(3400): note: Siehe Deklaration von "v8::Object"
node_modules\homebridge-ranger\node_modules\curve25519-n2\node_curve.cc(34): error C2065: "target": nichtdeklarierter Bezeichner [C:\Users\chris\AppData\Roaming\npm\node_modules\homebridge-ranger\node_modules\curve25519-n2\build\curve.vcxproj]
node_modules\curve25519-n2\node_curve.cc(34): error C2182: "init": Unzulässige Verwendung des Typs "void" [C:\Users\chris\AppData\Roaming\npm\node_modules\homebridge-ranger\node_modules\curve25519-n2\build\curve.vcxproj]
node_modules\curve25519-n2\node_curve.cc(34): error C2448: "init": Funktionsstil-Initialisierung scheint eine Funktionsdefinition zu sein [C:\Users\chris\AppData\Roaming\npm\node_modules\homebridge-ranger\node_modules\curve25519-n2\build\curve.vcxproj]
node_modules\curve25519-n2\node_curve.cc(40): warning C4312: "Typumwandlung": Konvertierung von "int" in größeren Typ "node::addon_register_func" [C:\Users\chris\AppData\Roaming\npm\node_modules\homebridge-ranger\node_modules\curve25519-n2\build\curve.vcxproj]
```
... and Í have no idea what "Handle" is from or what typie it is or how to fix "v8::Value::ToObject"

**Comment by jsveron23** [comment]
maybe it could help?

`brew install libsodium`

**Comment by MystK** [comment]
this should be fixed. Please try again
